"""change unique in scenario

Revision ID: 041fe872b7e0
Revises: 201b8da92838
Create Date: 2023-10-06 16:32:33.462450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041fe872b7e0'
down_revision: Union[str, None] = '201b8da92838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capex_scenario_id', table_name='capex')
    op.create_index(op.f('ix_capex_scenario_id'), 'capex', ['scenario_id'], unique=False)
    op.drop_index('ix_credits_scenario_id', table_name='credits')
    op.create_index(op.f('ix_credits_scenario_id'), 'credits', ['scenario_id'], unique=False)
    op.drop_index('ix_expenses_scenario_id', table_name='expenses')
    op.create_index(op.f('ix_expenses_scenario_id'), 'expenses', ['scenario_id'], unique=False)
    op.drop_index('ix_leasings_scenario_id', table_name='leasings')
    op.create_index(op.f('ix_leasings_scenario_id'), 'leasings', ['scenario_id'], unique=False)
    op.drop_index('ix_own_funds_scenario_id', table_name='own_funds')
    op.create_index(op.f('ix_own_funds_scenario_id'), 'own_funds', ['scenario_id'], unique=False)
    op.drop_index('ix_purchases_scenario_id', table_name='purchases')
    op.create_index(op.f('ix_purchases_scenario_id'), 'purchases', ['scenario_id'], unique=False)
    op.drop_index('ix_sales_scenario_id', table_name='sales')
    op.create_index(op.f('ix_sales_scenario_id'), 'sales', ['scenario_id'], unique=False)
    op.drop_index('ix_taxes_scenario_id', table_name='taxes')
    op.create_index(op.f('ix_taxes_scenario_id'), 'taxes', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxes_scenario_id'), table_name='taxes')
    op.create_index('ix_taxes_scenario_id', 'taxes', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_sales_scenario_id'), table_name='sales')
    op.create_index('ix_sales_scenario_id', 'sales', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_purchases_scenario_id'), table_name='purchases')
    op.create_index('ix_purchases_scenario_id', 'purchases', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_own_funds_scenario_id'), table_name='own_funds')
    op.create_index('ix_own_funds_scenario_id', 'own_funds', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_leasings_scenario_id'), table_name='leasings')
    op.create_index('ix_leasings_scenario_id', 'leasings', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_expenses_scenario_id'), table_name='expenses')
    op.create_index('ix_expenses_scenario_id', 'expenses', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_credits_scenario_id'), table_name='credits')
    op.create_index('ix_credits_scenario_id', 'credits', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_capex_scenario_id'), table_name='capex')
    op.create_index('ix_capex_scenario_id', 'capex', ['scenario_id'], unique=False)
    # ### end Alembic commands ###
