"""change unique

Revision ID: d7b7c8430784
Revises: 041fe872b7e0
Create Date: 2023-10-06 16:33:38.647208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b7c8430784'
down_revision: Union[str, None] = '041fe872b7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_balance_sheet_scenario_id', table_name='balance_sheet')
    op.create_index(op.f('ix_balance_sheet_scenario_id'), 'balance_sheet', ['scenario_id'], unique=False)
    op.drop_index('ix_cash_flow_plan_scenario_id', table_name='cash_flow_plan')
    op.create_index(op.f('ix_cash_flow_plan_scenario_id'), 'cash_flow_plan', ['scenario_id'], unique=False)
    op.drop_index('ix_financial_ratios_scenario_id', table_name='financial_ratios')
    op.create_index(op.f('ix_financial_ratios_scenario_id'), 'financial_ratios', ['scenario_id'], unique=False)
    op.drop_index('ix_profit_loss_plan_scenario_id', table_name='profit_loss_plan')
    op.create_index(op.f('ix_profit_loss_plan_scenario_id'), 'profit_loss_plan', ['scenario_id'], unique=False)
    op.drop_index('ix_project_details_scenario_id', table_name='project_details')
    op.create_index(op.f('ix_project_details_scenario_id'), 'project_details', ['scenario_id'], unique=False)
    op.drop_index('ix_sales_plan_scenario_id', table_name='sales_plan')
    op.create_index(op.f('ix_sales_plan_scenario_id'), 'sales_plan', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_plan_scenario_id'), table_name='sales_plan')
    op.create_index('ix_sales_plan_scenario_id', 'sales_plan', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_project_details_scenario_id'), table_name='project_details')
    op.create_index('ix_project_details_scenario_id', 'project_details', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_profit_loss_plan_scenario_id'), table_name='profit_loss_plan')
    op.create_index('ix_profit_loss_plan_scenario_id', 'profit_loss_plan', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_financial_ratios_scenario_id'), table_name='financial_ratios')
    op.create_index('ix_financial_ratios_scenario_id', 'financial_ratios', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_cash_flow_plan_scenario_id'), table_name='cash_flow_plan')
    op.create_index('ix_cash_flow_plan_scenario_id', 'cash_flow_plan', ['scenario_id'], unique=False)
    op.drop_index(op.f('ix_balance_sheet_scenario_id'), table_name='balance_sheet')
    op.create_index('ix_balance_sheet_scenario_id', 'balance_sheet', ['scenario_id'], unique=False)
    # ### end Alembic commands ###
