"""change scenario_field

Revision ID: 201b8da92838
Revises: 200aad3efdbb
Create Date: 2023-10-06 16:22:16.284980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201b8da92838'
down_revision: Union[str, None] = '200aad3efdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_sheet', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.drop_index('ix_balance_sheet_scenario', table_name='balance_sheet')
    op.create_index(op.f('ix_balance_sheet_scenario_id'), 'balance_sheet', ['scenario_id'], unique=True)
    op.drop_column('balance_sheet', 'scenario')
    op.add_column('cash_flow_plan', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.drop_index('ix_cash_flow_plan_scenario', table_name='cash_flow_plan')
    op.create_index(op.f('ix_cash_flow_plan_scenario_id'), 'cash_flow_plan', ['scenario_id'], unique=True)
    op.drop_column('cash_flow_plan', 'scenario')
    op.add_column('financial_ratios', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.drop_index('ix_financial_ratios_scenario', table_name='financial_ratios')
    op.create_index(op.f('ix_financial_ratios_scenario_id'), 'financial_ratios', ['scenario_id'], unique=True)
    op.drop_column('financial_ratios', 'scenario')
    op.add_column('profit_loss_plan', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.drop_index('ix_profit_loss_plan_scenario', table_name='profit_loss_plan')
    op.create_index(op.f('ix_profit_loss_plan_scenario_id'), 'profit_loss_plan', ['scenario_id'], unique=True)
    op.drop_column('profit_loss_plan', 'scenario')
    op.add_column('sales_plan', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.drop_index('ix_sales_plan_scenario', table_name='sales_plan')
    op.create_index(op.f('ix_sales_plan_scenario_id'), 'sales_plan', ['scenario_id'], unique=True)
    op.drop_column('sales_plan', 'scenario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_plan', sa.Column('scenario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sales_plan_scenario_id'), table_name='sales_plan')
    op.create_index('ix_sales_plan_scenario', 'sales_plan', ['scenario'], unique=False)
    op.drop_column('sales_plan', 'scenario_id')
    op.add_column('profit_loss_plan', sa.Column('scenario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_profit_loss_plan_scenario_id'), table_name='profit_loss_plan')
    op.create_index('ix_profit_loss_plan_scenario', 'profit_loss_plan', ['scenario'], unique=False)
    op.drop_column('profit_loss_plan', 'scenario_id')
    op.add_column('financial_ratios', sa.Column('scenario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_financial_ratios_scenario_id'), table_name='financial_ratios')
    op.create_index('ix_financial_ratios_scenario', 'financial_ratios', ['scenario'], unique=False)
    op.drop_column('financial_ratios', 'scenario_id')
    op.add_column('cash_flow_plan', sa.Column('scenario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cash_flow_plan_scenario_id'), table_name='cash_flow_plan')
    op.create_index('ix_cash_flow_plan_scenario', 'cash_flow_plan', ['scenario'], unique=False)
    op.drop_column('cash_flow_plan', 'scenario_id')
    op.add_column('balance_sheet', sa.Column('scenario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_balance_sheet_scenario_id'), table_name='balance_sheet')
    op.create_index('ix_balance_sheet_scenario', 'balance_sheet', ['scenario'], unique=False)
    op.drop_column('balance_sheet', 'scenario_id')
    # ### end Alembic commands ###
