"""Initial migration

Revision ID: d8428ca8ab9d
Revises: 
Create Date: 2023-10-06 08:37:26.788082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8428ca8ab9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('fixed_assets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_non_current_assets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inventories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_on_purchases', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accounts_receivable', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_current_assets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('share_capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retained_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('borrowed_funds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accounts_payable', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_liabilities_and_equity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_sheet_project'), 'balance_sheet', ['project'], unique=True)
    op.create_table('capex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('depreciation_period', sa.Integer(), nullable=False),
    sa.Column('is_leasing', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capex_id'), 'capex', ['id'], unique=False)
    op.create_table('cash_flow_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('working_capital_change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operating_cash_flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_refund', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capital_expense_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('liquidation_expense_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('liquidation_income_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('investment_cash_flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('owner_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loan_receipt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loan_repayment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('financing_cash_flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beginning_cash_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ending_cash_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flow_plan_project'), 'cash_flow_plan', ['project'], unique=True)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('activity_classification', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('ros', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('asset_turnover', sa.Float(), nullable=True),
    sa.Column('current_assets_turnover', sa.Float(), nullable=True),
    sa.Column('inventory_turnover', sa.Float(), nullable=True),
    sa.Column('accounts_receivable_turnover', sa.Float(), nullable=True),
    sa.Column('accounts_payable_turnover', sa.Float(), nullable=True),
    sa.Column('autonomy', sa.Float(), nullable=True),
    sa.Column('leverage_de', sa.Float(), nullable=True),
    sa.Column('own_working_capital', sa.Float(), nullable=True),
    sa.Column('absolute_liquidity', sa.Float(), nullable=True),
    sa.Column('interim_liquidity', sa.Float(), nullable=True),
    sa.Column('current_liquidity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_ratios_project'), 'financial_ratios', ['project'], unique=True)
    op.create_table('leasings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('leasing_id', sa.String(length=100), nullable=True),
    sa.Column('lessor', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('own_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('investor', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profit_loss_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operating_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('management_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ebit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_before_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ebitda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_loss_plan_project'), 'profit_loss_plan', ['project'], unique=True)
    op.create_table('project_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('project_rating', sa.Float(), nullable=True),
    sa.Column('capex_with_vat', sa.Float(), nullable=True),
    sa.Column('own_funds', sa.Float(), nullable=True),
    sa.Column('borrowed_funds', sa.Float(), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.Float(), nullable=True),
    sa.Column('average_debt_to_ebitda_ratio', sa.Float(), nullable=True),
    sa.Column('annual_revenue_excluding_vat', sa.Float(), nullable=True),
    sa.Column('annual_operating_expenses', sa.Float(), nullable=True),
    sa.Column('annual_net_profit', sa.Float(), nullable=True),
    sa.Column('average_sales_profitability', sa.Float(), nullable=True),
    sa.Column('annual_vat', sa.Float(), nullable=True),
    sa.Column('annual_income_tax', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('refinancing_rate', sa.Float(), nullable=True),
    sa.Column('net_present_value', sa.Float(), nullable=True),
    sa.Column('profitability_index', sa.Float(), nullable=True),
    sa.Column('internal_rate_of_return', sa.Float(), nullable=True),
    sa.Column('modified_internal_rate_of_return', sa.Float(), nullable=True),
    sa.Column('nominal_payback_period', sa.Float(), nullable=True),
    sa.Column('discounted_payback_period', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_details_project'), 'project_details', ['project'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmc', sa.Float(), nullable=True),
    sa.Column('customer_advances', sa.Float(), nullable=True),
    sa.Column('customer_accounts_receivable', sa.Float(), nullable=True),
    sa.Column('supplier_advances', sa.Float(), nullable=True),
    sa.Column('supplier_accounts_payable', sa.Float(), nullable=True),
    sa.Column('vat_balance_on_purchased_assets', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('project', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('revenue_with_vat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_plan_project'), 'sales_plan', ['project'], unique=True)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxes_id'), 'taxes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxes_id'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_sales_plan_project'), table_name='sales_plan')
    op.drop_table('sales_plan')
    op.drop_table('sales')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_project_details_project'), table_name='project_details')
    op.drop_table('project_details')
    op.drop_index(op.f('ix_profit_loss_plan_project'), table_name='profit_loss_plan')
    op.drop_table('profit_loss_plan')
    op.drop_table('own_funds')
    op.drop_table('leasings')
    op.drop_index(op.f('ix_financial_ratios_project'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('credits')
    op.drop_index(op.f('ix_cash_flow_plan_project'), table_name='cash_flow_plan')
    op.drop_table('cash_flow_plan')
    op.drop_index(op.f('ix_capex_id'), table_name='capex')
    op.drop_table('capex')
    op.drop_index(op.f('ix_balance_sheet_project'), table_name='balance_sheet')
    op.drop_table('balance_sheet')
    # ### end Alembic commands ###
